app_name: deanet
app_title: deanet
default_title: "deanet: Digital Environment A Network Evolution Technology "
sub_title: "Digital News"
app_url: http://deanet.web.id
rss_url: http://feeds.feedburner.com/deanet
meta_keywords: "digital, binary, quantum, technology, religion, culture, robotics, genetics, sysadmin, sysadmin news, sysadmin day, kernel, tweaking, tunning"
meta_author: "deanet"
body_class: home

# Set this to true for a more fancy interface, but for the cost of page load time
uses_javascript: false

# Edit expiration default: 60 (this means that editing ends 60 minutes after last update of item)
# Set to 0 or omit to always allow editing of items by its owner
edit_expiration_in_minutes: 60

 ga: UA-12495571-6
sidebar: |-
          <h2>What is this ?</h2>
          <ul>
            <li id='learning-documentation'>
              <h3></h3>
              <p>
                Free post a part of your blog, website, or other sites on here.
                Free sharing of science, culture, religion, and technology.
              </p>
            </li>
            <li id='learning-bugs'>
              <h3>Free</h3>
              <p>
                All features on here is free, we aren't asking of payment.
              </p>
            </li>
            <li id='learning-getting-help'>
              <h3>How to post ?</h3>
              <p>
                Click <a href='/items/new'>here</a> for a new post. You do not need to register first
                <em>Note, For the prevention of spam, then the links that you entered is not linked</em>
              </p>
            </li>
          </ul>
