#!/usr/bin/env ruby


require  'domainredirect.rb'

# This is how you use and configure Rack::DomainRedirect middleware
use Rack::DomainRedirect, ['beta.deanet.web.id', '192.168.0.177']


require File.dirname(__FILE__) + '/../config/boot'
require 'commands/server'
